SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ingredient](
  [id] [bigint] IDENTITY(1,1) NOT NULL,
  [amount] [numeric](19, 2) NULL,
  [description] [varchar](255) NULL,
  [recipe_id] [bigint] NULL,
  [uom_id] [bigint] NULL,
  PRIMARY KEY CLUSTERED
    (
      [id] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO