SET IDENTITY_INSERT [dbo].[ingredient] ON
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (1, CAST(2.00 AS Numeric(19, 2)), N'Ripe avocados', 1, 5)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (2, CAST(5.00 AS Numeric(19, 2)), N'Kosher salt', 1, 2)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (3, CAST(2.00 AS Numeric(19, 2)), N'Fresh lime juice or lemon juice', 1, 1)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (4, CAST(2.00 AS Numeric(19, 2)), N'Minced red onion or thinly sliced green onion', 1, 5)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (5, CAST(2.00 AS Numeric(19, 2)), N'Serrano chiles, stems and seeds removed minced', 1, 5)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (6, CAST(2.00 AS Numeric(19, 2)), N'Cilantro', 1, 1)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (7, CAST(2.00 AS Numeric(19, 2)), N'Freshly grated black pepper', 1, 8)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (8, CAST(5.00 AS Numeric(19, 2)), N'Ripe tomato seeds and pulp removed, chopped', 1, 5)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (9, CAST(2.00 AS Numeric(19, 2)), N'Ancho Chili Powder', 2, 1)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (10, CAST(1.00 AS Numeric(19, 2)), N'Dried Oregano', 2, 1)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (11, CAST(1.00 AS Numeric(19, 2)), N'Dried cumin', 2, 2)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (12, CAST(1.00 AS Numeric(19, 2)), N'Sugar', 2, 2)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (13, CAST(5.00 AS Numeric(19, 2)), N'Salt', 2, 2)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (14, CAST(1.00 AS Numeric(19, 2)), N'Clove of garlic, chopped', 2, 5)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (15, CAST(1.00 AS Numeric(19, 2)), N'finely grated orance zestr', 2, 1)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (16, CAST(3.00 AS Numeric(19, 2)), N'fresh-squeezed orange juice', 2, 1)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (17, CAST(2.00 AS Numeric(19, 2)), N'Olive oil', 2, 1)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (18, CAST(4.00 AS Numeric(19, 2)), N'Boneless chicken thighs', 2, 1)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (19, CAST(8.00 AS Numeric(19, 2)), N'Small corn tortillas', 2, 5)
INSERT [dbo].[ingredient] ([id], [amount], [description], [recipe_id], [uom_id]) VALUES (20, CAST(8.00 AS Numeric(19, 2)), N'Packed baby arugula', 2, 5)
SET IDENTITY_INSERT [dbo].[ingredient] OFF